# Generated by Django 3.1.7 on 2021-03-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='이메일'),
            preserve_default=False,
        ),
    ]
